### ISSUE TITLE
go 1.13 custom errors

### ISSUE THREAD

**Issue by karthikraobr** [uber-go/guide#39] opened 2019-10-14 11:46 UTC
https://peter.bourgon.org/blog/2019/09/11/programming-with-errors.html

Would this be a better way to handle/check custom errors?

**Comment by skaldesh** [comment] 2019-10-25 10:18
also related to #8

**Comment by mway** [comment] 2019-10-29 13:53
Duplicate of #8.

**Closed by mway** 2019-10-29 13:53 UTC
